baseurl = "http://anhnk.github.io/"
languageCode = "en-us"
title = "Anh Do"

[[menu.main]]
  name = "About"
  pre = "<i class='fa fa-heart'></i>"
  weight = -110
  identifier = "about"
  url = "/about/"
